version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_container
    environment:
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      # Redis 的密码设置在 redis.conf 配置文件中，而不是通过环境变量
      # 因此，我们使用命令来启动 Redis 并设置密码
    command: redis-server --save 60 1 --loglevel verbose --requirepass redis123
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: